# Generated by Django 5.2.14 on 2026-06-14 08:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.migrations.operations.special
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# accounts.migrations.0054_auto_20260521_1800
# accounts.migrations.0056_set_db_cascade_on_user_relations
# accounts.migrations.0057_fix_classroom_teacher_uniqueness
# accounts.migrations.0059_populate_classroom_grade_levels
# accounts.migrations.0065_fix_empty_emails
# accounts.migrations.0085_convert_teacher_roles

class Migration(migrations.Migration):

    replaces = [('accounts', '0001_initial'), ('accounts', '0002_classroom_studentclassenrollment'), ('accounts', '0003_studentclassenrollment_q1_studentclassenrollment_q2_and_more'), ('accounts', '0004_alter_studentclassenrollment_q1_and_more'), ('accounts', '0005_announcement'), ('accounts', '0006_announcement_attachment'), ('accounts', '0007_attendance'), ('accounts', '0008_learningmaterial'), ('accounts', '0009_anecdotalrecord'), ('accounts', '0010_corevaluesgrade'), ('accounts', '0011_parentcommunication'), ('accounts', '0012_subject_profile_registration_number_scratchcard_fee'), ('accounts', '0013_profile_contact_information_profile_father_name_and_more'), ('accounts', '0014_notification'), ('accounts', '0015_enrollmentapplication'), ('accounts', '0016_websitecontent'), ('accounts', '0017_alter_websitecontent_section_key'), ('accounts', '0018_enrollmentapplication_birth_certificate_and_more'), ('accounts', '0019_alter_websitecontent_section_key'), ('accounts', '0020_alter_websitecontent_options_and_more'), ('accounts', '0021_announcement_is_public'), ('accounts', '0022_announcement_expiration_date_announcement_priority_and_more'), ('accounts', '0023_announcement_read_by_and_more'), ('accounts', '0024_user_is_approved_user_is_verified_otp'), ('accounts', '0025_gradereport_grade'), ('accounts', '0026_classroomsubject'), ('accounts', '0027_remove_subject_units'), ('accounts', '0028_add_grade_weights_to_classroomsubject'), ('accounts', '0029_add_middle_name_to_profile'), ('accounts', '0030_announcementattachment'), ('accounts', '0031_alter_grade_options_alter_grade_unique_together_and_more'), ('accounts', '0032_profile_title'), ('accounts', '0033_alter_corevaluesgrade_unique_together_and_more'), ('accounts', '0034_user_last_activity'), ('accounts', '0035_chatroom_chatmessage'), ('accounts', '0036_friendship'), ('accounts', '0037_chatmessage_is_pinned_chatroom_pinned_by_and_more'), ('accounts', '0038_add_is_delivered_to_chatmessage'), ('accounts', '0039_add_is_edited_to_chatmessage'), ('accounts', '0040_add_created_by_to_chatroom'), ('accounts', '0041_alter_websitecontent_options_websitecontent_category_and_more'), ('accounts', '0042_alter_websitecontent_section'), ('accounts', '0043_websitecontent_image_alter_websitecontent_content'), ('accounts', '0044_systemsetting'), ('accounts', '0045_chatmessage_parent_message_messagereaction'), ('accounts', '0046_chatroom_last_action_content_and_more'), ('accounts', '0047_profile_lrn_emailverificationtoken'), ('accounts', '0048_remove_otp_code_otp_expires_at_otp_hashed_code_and_more'), ('accounts', '0049_delete_emailverificationtoken'), ('accounts', '0050_rename_expiration_date_announcement_event_date'), ('accounts', '0051_announcement_end_date'), ('accounts', '0052_announcement_target_classrooms_and_more'), ('accounts', '0053_profile_profile_picture_user_account_status_and_more'), ('accounts', '0054_auto_20260521_1800'), ('accounts', '0055_user_temp_password_storage'), ('accounts', '0056_set_db_cascade_on_user_relations'), ('accounts', '0057_fix_classroom_teacher_uniqueness'), ('accounts', '0058_classroom_grade_level'), ('accounts', '0059_populate_classroom_grade_levels'), ('accounts', '0060_reportedmessage_resolved_by'), ('accounts', '0061_reportedmessage_message_content_snapshot_and_more'), ('accounts', '0062_room_timeslot_schedule'), ('accounts', '0063_fcmtoken'), ('accounts', '0064_notification_improvements'), ('accounts', '0065_fix_empty_emails'), ('accounts', '0066_add_friend_request_notification_type'), ('accounts', '0067_remove_user_temp_password_storage'), ('accounts', '0068_migrate_filefields_to_supabase_urls'), ('accounts', '0069_onboardingstate'), ('accounts', '0070_announcementcomment'), ('accounts', '0071_chatmessage_attachments'), ('accounts', '0072_enrollment_workflow_fields'), ('accounts', '0073_nullable_parent_fields'), ('accounts', '0074_classroom_capacity'), ('accounts', '0075_enrollment_enhancements'), ('accounts', '0076_enrollment_lrn_request'), ('accounts', '0077_enrollment_temp_password'), ('accounts', '0078_fix_lrn_request_reason_length'), ('accounts', '0079_timeslot_add_classroom'), ('accounts', '0080_alter_enrollmentapplication_strand'), ('accounts', '0081_add_performance_indexes'), ('accounts', '0082_schedule_attendance'), ('accounts', '0083_departmentcontact_ticket_ticketattachment_and_more'), ('accounts', '0084_user_staff_title_alter_onboardingstate_role_and_more'), ('accounts', '0085_convert_teacher_roles'), ('accounts', '0086_user_additional_roles'), ('accounts', '0087_ticket_soft_delete_sla_and_indexes'), ('accounts', '0088_add_performance_indexes'), ('accounts', '0089_add_academic_level_to_systemsetting'), ('accounts', '0090_remove_transmuted_score'), ('accounts', '0091_add_default_grading_weights_to_systemsetting')]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('portal', '0006_academicyear_is_archived_alter_auditlog_action_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], default='student', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('is_approved', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_reset', 'Pending Password Reset')], default='active', max_length=20)),
                ('must_change_password', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classrooms', to=settings.AUTH_USER_MODEL)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='portal.academicyear')),
                ('description', models.TextField(blank=True, null=True)),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='portal.semester')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
                ('q1', models.IntegerField(blank=True, null=True)),
                ('q2', models.IntegerField(blank=True, null=True)),
                ('q3', models.IntegerField(blank=True, null=True)),
                ('q4', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['student__username'],
                'unique_together': {('student', 'classroom')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.classroom')),
                ('marked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marked_attendances', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'student__username'],
                'unique_together': {('student', 'classroom', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('dlp', 'Daily Lesson Plan (DLP)'), ('dll', 'Daily Lesson Log (DLL)'), ('module', 'Learning Module'), ('activity', 'Learning Activity Sheet'), ('assessment', 'Assessment Material'), ('other', 'Other')], default='dlp', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('quarter', models.IntegerField(blank=True, help_text='Quarter (1-4)', null=True)),
                ('week', models.IntegerField(blank=True, help_text='Week number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.classroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('grade_level', models.CharField(help_text='Grade level this subject is for', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['grade_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScratchCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=12, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scratch_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('tuition', 'Tuition Fee'), ('miscellaneous', 'Miscellaneous Fee'), ('books', 'Books/Materials'), ('uniform', 'Uniform'), ('other', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partially Paid'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(blank=True, help_text='For students', max_length=20, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='For teachers', max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('registration_number', models.CharField(blank=True, help_text='Auto-generated unique registration number for students', max_length=20, null=True, unique=True)),
                ('contact_information', models.TextField(blank=True, help_text='Additional contact details', null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], help_text='Honorific title for teachers', max_length=10, null=True)),
                ('lrn', models.CharField(blank=True, help_text='Learner Reference Number (12 digits)', max_length=12, null=True)),
                ('is_suspended', models.BooleanField(default=False)),
                ('linked_students', models.ManyToManyField(blank=True, limit_choices_to={'role': 'student'}, related_name='parent_profiles', to=settings.AUTH_USER_MODEL)),
                ('mute_until', models.DateTimeField(blank=True, null=True)),
                ('profile_picture', models.URLField(blank=True, help_text='Supabase Storage URL for profile picture', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('announcement', 'Announcement'), ('grade', 'Grade Update'), ('attendance', 'Attendance'), ('fee', 'Fee Reminder'), ('system', 'System')], default='system', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.URLField(blank=True, help_text='Optional link to redirect user when clicked', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sex', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=200, null=True)),
                ('nationality', models.CharField(default='Filipino', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('street_address', models.CharField(max_length=200)),
                ('barangay', models.CharField(max_length=100)),
                ('city_municipality', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('father_name', models.CharField(max_length=200)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('mother_name', models.CharField(max_length=200)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=200, null=True)),
                ('guardian_relationship', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('grade_level', models.CharField(choices=[('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2)),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True)),
                ('previous_school_address', models.TextField(blank=True, null=True)),
                ('lrn', models.CharField(blank=True, help_text='Learner Reference Number', max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('emergency_contact_relationship', models.CharField(max_length=50)),
                ('emergency_contact_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='enrollment_documents/birth_certificates/')),
                ('certificate_of_completion', models.FileField(blank=True, help_text='Grade 10 Candidate for Completion Certificate', null=True, upload_to='enrollment_documents/completion_certificates/')),
                ('form_138', models.FileField(blank=True, help_text='Grade 6 Candidate for Graduation Certificate', null=True, upload_to='enrollment_documents/form_138/')),
                ('good_moral_certificate', models.FileField(blank=True, null=True, upload_to='enrollment_documents/good_moral/')),
                ('is_als', models.BooleanField(default=False, help_text='Alternative Learning System applicant')),
                ('last_school_attended_cert', models.FileField(blank=True, help_text='For ALS applicants', null=True, upload_to='enrollment_documents/last_school/')),
                ('report_card', models.FileField(blank=True, null=True, upload_to='enrollment_documents/report_cards/')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('section', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('category', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('programs', 'Programs Page'), ('other', 'Other')], default='other', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='website_content/')),
            ],
            options={
                'ordering': ['category', 'section'],
                'verbose_name': 'Website Content',
                'verbose_name_plural': 'Website Contents',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General'), ('system_update', 'System Update'), ('emergency', 'Emergency'), ('academic', 'Academic'), ('events', 'Events'), ('holiday', 'Holiday')], default='general', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_announcements', to=settings.AUTH_USER_MODEL)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='announcements/attachments/')),
                ('is_public', models.BooleanField(default=False)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('info', 'Info'), ('critical', 'Critical')], default='info', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('expired', 'Expired')], default='draft', max_length=10)),
                ('target_audience', models.CharField(choices=[('all', 'All Users'), ('admins', 'Admins'), ('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents')], default='all', max_length=20)),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_announcements', to=settings.AUTH_USER_MODEL)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('target_classrooms', models.ManyToManyField(blank=True, related_name='announcements', to='accounts.classroom')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('school_year', models.CharField(default='2025-2026', max_length=20)),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_subjects', models.IntegerField(default=0)),
                ('passed_subjects', models.IntegerField(default=0)),
                ('failed_subjects', models.IntegerField(default=0)),
                ('overall_remarks', models.TextField(blank=True, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False, help_text='Final report for the school year')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_grade_reports', to='accounts.classroom')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-school_year', '-quarter', 'student__username'],
                'unique_together': {('student', 'classroom', 'quarter', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='accounts.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='accounts.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classroom_subjects', to=settings.AUTH_USER_MODEL)),
                ('pt_weight', models.DecimalField(decimal_places=2, default=50.0, help_text='Performance Task weight (%)', max_digits=5)),
                ('qa_weight', models.DecimalField(decimal_places=2, default=20.0, help_text='Quarterly Assessment weight (%)', max_digits=5)),
                ('ww_weight', models.DecimalField(decimal_places=2, default=30.0, help_text='Written Work weight (%)', max_digits=5)),
            ],
            options={
                'ordering': ['classroom__name', 'subject__name'],
                'unique_together': {('classroom', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='announcements/attachments/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.announcement')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('quarterly_assessment', 'Quarterly Assessment'), ('final_grade', 'Final Grade')], default='written_work', max_length=30)),
                ('quarter', models.IntegerField(choices=[(1, 'First Quarter'), (2, 'Second Quarter'), (3, 'Third Quarter'), (4, 'Fourth Quarter')])),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('transmuted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('computed_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Prevents further edits after submission')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='accounts.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='accounts.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subject_grades', to=settings.AUTH_USER_MODEL)),
                ('academic_year', models.CharField(default='2025-2026', max_length=20)),
            ],
            options={
                'ordering': ['-academic_year', '-quarter', 'subject__name', 'grade_type'],
                'unique_together': {('student', 'subject', 'grade_type', 'quarter', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='chat_rooms', to=settings.AUTH_USER_MODEL)),
                ('pinned_by', models.ManyToManyField(blank=True, related_name='pinned_rooms', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rooms', to=settings.AUTH_USER_MODEL)),
                ('last_action_content', models.TextField(blank=True, null=True)),
                ('last_action_sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_actions', to=settings.AUTH_USER_MODEL)),
                ('last_action_type', models.CharField(default='message', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requests_received', to=settings.AUTH_USER_MODEL)),
                ('is_pinned_by_from', models.BooleanField(default=False)),
                ('is_pinned_by_to', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='School Portal', max_length=255)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='The portal is currently undergoing maintenance. Please check back later.')),
                ('current_quarter', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')], default='1', max_length=1)),
                ('academic_year', models.CharField(default='2025-2026', max_length=9)),
                ('enrollment_open', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_student_chat', models.BooleanField(default=True)),
                ('allow_teacher_chat', models.BooleanField(default=True)),
                ('primary_color', models.CharField(default='#2D1B4D', max_length=7)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('school_logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('school_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_color', models.CharField(default='#9F7AEA', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='accounts.chatmessage')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MessageReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='accounts.chatmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('message', 'user', 'emoji')},
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL)),
                ('expires_at', models.DateTimeField(null=True)),
                ('hashed_code', models.CharField(default='', max_length=128)),
                ('otp_type', models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password Reset')], default='signup', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignments/')),
                ('due_date', models.DateTimeField()),
                ('points', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='ReportedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='pending', max_length=20)),
                ('moderator_note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='accounts.chatmessage')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='accounts.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.RunPython(
            code=accounts.migrations.0054_auto_20260521_1800.convert_empty_emails_to_null,
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password_storage',
            field=models.CharField(blank=True, help_text='Stored temporary password until first login/change', max_length=128, null=True),
        ),
        migrations.RunPython(
            code=accounts.migrations.0056_set_db_cascade_on_user_relations.set_cascade_on_postgres,
            reverse_code=accounts.migrations.0056_set_db_cascade_on_user_relations.reverse_cascade_on_postgres,
        ),
        migrations.RunPython(
            code=accounts.migrations.0057_fix_classroom_teacher_uniqueness.fix_duplicate_teachers,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='The advisory teacher for this classroom. Each teacher can only have one advisory classroom.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classroom', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Academic grade level for this classroom (e.g., Grade 7)', max_length=20, null=True),
        ),
        migrations.RunPython(
            code=accounts.migrations.0059_populate_classroom_grade_levels.populate_classroom_grade_levels,
            reverse_code=django.db.migrations.operations.special.RunPython.noop,
        ),
        migrations.AddField(
            model_name='reportedmessage',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reportedmessage',
            name='message_content_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportedmessage',
            name='reported_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportedmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.chatmessage'),
        ),
        migrations.AlterField(
            model_name='reportedmessage',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Room 204, Science Lab, Gym', max_length=100)),
                ('building', models.CharField(blank=True, max_length=100, null=True)),
                ('capacity', models.IntegerField(default=40)),
                ('room_type', models.CharField(choices=[('classroom', 'Classroom'), ('laboratory', 'Laboratory'), ('gym', 'Gymnasium'), ('library', 'Library'), ('other', 'Other')], default='classroom', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('label', models.CharField(blank=True, help_text="Optional label, e.g. '1st Period'", max_length=50, null=True)),
            ],
            options={
                'ordering': ['day', 'start_time'],
                'unique_together': {('day', 'start_time', 'end_time')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='portal.academicyear')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.classroom')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='accounts.room')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='portal.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedules', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.timeslot')),
            ],
            options={
                'ordering': ['time_slot__day', 'time_slot__start_time'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'time_slot', 'academic_year'), name='unique_teacher_timeslot_year'), models.UniqueConstraint(condition=models.Q(('room__isnull', False)), fields=('room', 'time_slot', 'academic_year'), name='unique_room_timeslot_year'), models.UniqueConstraint(fields=('classroom', 'time_slot', 'academic_year'), name='unique_classroom_timeslot_year')],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web Browser'), ('android', 'Android'), ('ios', 'iOS')], default='web', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('grade', 'Grade Update'), ('attendance', 'Attendance'), ('fee', 'Fee Reminder'), ('message', 'Message'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Relative or absolute URL to redirect user when clicked', max_length=500, null=True),
        ),
        migrations.RunPython(
            code=accounts.migrations.0065_fix_empty_emails.fix_empty_emails,
            reverse_code=accounts.migrations.0065_fix_empty_emails.reverse_fix,
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('grade', 'Grade Update'), ('attendance', 'Attendance'), ('fee', 'Fee Reminder'), ('message', 'Message'), ('friend_request', 'Friend Request'), ('system', 'System')], default='system', max_length=20),
        ),
        migrations.RemoveField(
            model_name='user',
            name='temp_password_storage',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='attachment',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='announcementattachment',
            name='file',
            field=models.URLField(help_text='Supabase Storage URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcementattachment',
            name='content_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='learningmaterial',
            name='file',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='learningmaterial',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='file',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='assignment',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.URLField(help_text='Supabase Storage URL', max_length=1000),
        ),
        migrations.AddField(
            model_name='submission',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='birth_certificate',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='report_card',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='form_138',
            field=models.URLField(blank=True, help_text='Grade 6 Candidate for Graduation Certificate', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='certificate_of_completion',
            field=models.URLField(blank=True, help_text='Grade 10 Candidate for Completion Certificate', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='good_moral_certificate',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='last_school_attended_cert',
            field=models.URLField(blank=True, help_text='For ALS applicants', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='school_logo',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='image',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=10)),
                ('has_seen_welcome', models.BooleanField(default=False)),
                ('completed_tutorials', models.JSONField(blank=True, default=list)),
                ('skipped_tutorials', models.JSONField(blank=True, default=list)),
                ('dismissed_tips', models.JSONField(blank=True, default=list)),
                ('checklist_progress', models.JSONField(blank=True, default=dict)),
                ('last_tutorial', models.CharField(blank=True, default='', max_length=100)),
                ('last_step_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.announcement')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_url',
            field=models.URLField(blank=True, help_text='Supabase Storage URL', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('file', 'File')], default='text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'PSA Birth Certificate'), ('report_card', 'Report Card'), ('form_138', 'Form 138 / Grade 6 Certificate'), ('certificate_of_completion', 'Certificate of Completion'), ('good_moral', 'Good Moral Certificate'), ('id_picture', 'ID Picture'), ('last_school_attended', 'Last School Attended Certificate'), ('other', 'Other Document')], max_length=30)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this document', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enrollment status histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='assigned_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='enrolled_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='enrollment_number',
            field=models.CharField(blank=True, help_text='Auto-generated ENR-YYYY-XXXXXX', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='enrollment_type',
            field=models.CharField(choices=[('new', 'New Student'), ('returning', 'Returning Student'), ('transferee', 'Transferee'), ('sh_applicant', 'SHS Applicant'), ('parent_assisted', 'Parent-Assisted Enrollment')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='strand',
            field=models.CharField(blank=True, choices=[('STEM', 'STEM'), ('ABM', 'ABM'), ('HUMSS', 'HUMSS'), ('GAS', 'GAS'), ('TVL-ICT', 'TVL-ICT'), ('TVL-HE', 'TVL-HE'), ('TVL-IA', 'TVL-IA'), ('TVL-AFA', 'TVL-AFA'), ('Sports', 'Sports'), ('Arts & Design', 'Arts & Design')], help_text='Required for Grades 11-12', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['status'], name='accounts_en_status_f24d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['enrollment_number'], name='accounts_en_enrollm_c9e064_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['grade_level'], name='accounts_en_grade_l_127727_idx'),
        ),
        migrations.AddField(
            model_name='enrollmentdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.enrollmentapplication'),
        ),
        migrations.AddField(
            model_name='enrollmentstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.enrollmentapplication'),
        ),
        migrations.AddField(
            model_name='enrollmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classroom',
            name='capacity',
            field=models.PositiveIntegerField(default=40, help_text='Maximum number of students allowed in this classroom'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='school_year',
            field=models.CharField(blank=True, help_text='School year applying for (e.g., 2026-2027)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='father_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='mother_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='id_picture',
            field=models.URLField(blank=True, help_text='Student ID Picture', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='linked_parent',
            field=models.ForeignKey(blank=True, help_text='Parent account linked during enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_enrollment_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who last reviewed this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['school_year'], name='accounts_en_school__6328e8_idx'),
        ),
        migrations.CreateModel(
            name='ParentLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(default='parent', help_text='Relationship to student (parent, guardian, etc.)', max_length=50)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary contact parent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='accounts.enrollmentapplication')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_parent_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'student')},
            },
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='temp_password_display',
            field=models.CharField(blank=True, help_text='Temporary password shown to applicant after enrollment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='lrn_request_reason',
            field=models.CharField(blank=True, help_text='Reason for not having LRN', max_length=200, null=True),
        ),
        migrations.RenameIndex(
            model_name='enrollmentapplication',
            new_name='accounts_en_school__6328e8_idx',
            old_name='accounts_enr_school__idx',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Scope this time slot to a specific section. Null = universal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='accounts.classroom'),
        ),
        migrations.AlterField(
            model_name='parentlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('classroom', 'day', 'start_time', 'end_time')},
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='strand',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic Track'), ('TechPro', 'Technical-Professional Track')], help_text='Required for Grades 11-12', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lrn',
            field=models.CharField(blank=True, db_index=True, help_text='Learner Reference Number (12 digits)', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_reset', 'Pending Password Reset')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, default='student', max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_read_idx'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='schedule',
            field=models.ForeignKey(blank=True, help_text='Links attendance to a specific schedule period. Null = class-level (adviser) attendance.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='accounts.schedule'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Denormalized from schedule for quick queries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='accounts.subject'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='time_slot',
            field=models.ForeignKey(blank=True, help_text='Denormalized from schedule for quick queries.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='accounts.timeslot'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', True)), fields=('student', 'classroom', 'date'), name='unique_class_level_attendance'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(condition=models.Q(('schedule__isnull', False)), fields=('student', 'schedule', 'date'), name='unique_schedule_attendance'),
        ),
        migrations.CreateModel(
            name='DepartmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('registrar', 'Registrar'), ('advisory', 'Advisory'), ('faculty', 'Faculty'), ('admin', "Principal's Office"), ('guidance', 'Guidance'), ('it', 'IT Support'), ('finance', 'Finance'), ('library', 'Library')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Department contacts',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('enrollment', 'Enrollment'), ('attendance', 'Attendance'), ('academic', 'Academic'), ('collaboration', 'Collaboration'), ('facilities', 'Facilities'), ('it_support', 'IT Support'), ('finance', 'Finance'), ('guidance', 'Guidance'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('replied', 'Replied'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('department', models.CharField(blank=True, default='', max_length=50)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField(max_length=500)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounts.ticket')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_messages', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('collaborator', 'Collaborator')], default='viewer', max_length=15)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='accounts.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ticket', 'user')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='staff_title',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('registrar', 'Registrar'), ('advisory', 'Advisory'), ('principal', 'Principal'), ('guidance_counselor', 'Guidance Counselor'), ('it_staff', 'IT Staff'), ('librarian', 'Librarian'), ('cashier', 'Cashier'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingstate',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, default='student', max_length=10),
        ),
        migrations.RunPython(
            code=accounts.migrations.0085_convert_teacher_roles.convert_teacher_roles,
            reverse_code=accounts.migrations.0085_convert_teacher_roles.reverse_convert,
        ),
        migrations.AddField(
            model_name='user',
            name='additional_roles',
            field=models.TextField(blank=True, default='', help_text='Comma-separated additional staff titles e.g. teacher,guidance_counselor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='first_response_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'category', 'assigned_to'], name='accounts_ti_status_4aa8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['created_by', 'status'], name='accounts_ti_created_f546ab_idx'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'timestamp'], name='idx_chatmsg_room_time'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['room', 'is_read', 'timestamp'], name='idx_chatmsg_room_read_time'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['status', 'created_at'], name='idx_friendship_status'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['from_user', 'status'], name='idx_friendship_from_status'),
        ),
        migrations.AddIndex(
            model_name='friendship',
            index=models.Index(fields=['to_user', 'status'], name='idx_friendship_to_status'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'category', '-created_at'], name='idx_announce_status_cat_time'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['status', 'target_audience', '-created_at'], name='idx_announce_status_audience'),
        ),
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(condition=models.Q(('event_date__isnull', False)), fields=['event_date'], name='idx_announce_event_date'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['academic_year', 'student'], name='idx_grade_year_student'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'subject', 'academic_year'], name='idx_grade_student_subject_year'),
        ),
        migrations.AddIndex(
            model_name='ticketparticipant',
            index=models.Index(fields=['user'], name='idx_ticketpart_user'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='idx_ticketmsg_ticket_time'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['sender', '-created_at'], name='idx_ticketmsg_sender_time'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['student', 'status'], name='idx_fee_student_status'),
        ),
        migrations.AddIndex(
            model_name='fee',
            index=models.Index(fields=['due_date', 'status'], name='idx_fee_due_status'),
        ),
        migrations.AddIndex(
            model_name='reportedmessage',
            index=models.Index(fields=['status', '-created_at'], name='idx_report_status_time'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['teacher', 'is_active'], name='idx_schedule_teacher_active'),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['classroom', 'is_active'], name='idx_schedule_class_active'),
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_status_cat_time',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_status_audience',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_event_date',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chatmsg_room_time',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chatmsg_room_read_time',
        ),
        migrations.RemoveIndex(
            model_name='fee',
            name='idx_fee_student_status',
        ),
        migrations.RemoveIndex(
            model_name='fee',
            name='idx_fee_due_status',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='idx_friendship_status',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='idx_friendship_from_status',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='idx_friendship_to_status',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_year_student',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_student_subject_year',
        ),
        migrations.RemoveIndex(
            model_name='reportedmessage',
            name='idx_report_status_time',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='idx_schedule_teacher_active',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='idx_schedule_class_active',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='idx_ticketmsg_ticket_time',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='idx_ticketmsg_sender_time',
        ),
        migrations.RemoveIndex(
            model_name='ticketparticipant',
            name='idx_ticketpart_user',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='accounts_ti_status_4aa8cc_idx',
            old_name='ticket_status_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='accounts_ti_created_f546ab_idx',
            old_name='ticket_creator_status_idx',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='academic_level',
            field=models.CharField(choices=[('jhs', 'Junior High School (Grades 7-10)'), ('shs', 'Senior High School (Grades 11-12)')], default='jhs', max_length=3),
        ),
        migrations.RemoveField(
            model_name='grade',
            name='transmuted_score',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_ww_weight',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Default Written Work weight (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_pt_weight',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Default Performance Task weight (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='default_qa_weight',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Default Quarterly Assessment weight (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='passing_grade',
            field=models.DecimalField(decimal_places=2, default=75.0, help_text='Minimum passing grade (%)', max_digits=5),
        ),
    ]
