# Generated by Django 4.2.30 on 2026-05-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classroom_studentclassenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentclassenrollment',
            name='q1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='q2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='q3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentclassenrollment',
            name='q4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
