# Generated by Django 4.2.30 on 2026-05-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentclassenrollment_q1_studentclassenrollment_q2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='q1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='q2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='q3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentclassenrollment',
            name='q4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
