# Generated by Django 4.2.30 on 2026-05-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='announcements/attachments/'),
        ),
    ]
