# Generated by Django 4.2.30 on 2026-05-02 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('material_type', models.CharField(choices=[('dlp', 'Daily Lesson Plan (DLP)'), ('dll', 'Daily Lesson Log (DLL)'), ('module', 'Learning Module'), ('activity', 'Learning Activity Sheet'), ('assessment', 'Assessment Material'), ('other', 'Other')], default='dlp', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/')),
                ('quarter', models.IntegerField(blank=True, help_text='Quarter (1-4)', null=True)),
                ('week', models.IntegerField(blank=True, help_text='Week number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='accounts.classroom')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
