# Generated by Django 4.2.30 on 2026-05-03 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_anecdotalrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoreValuesGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_type', models.CharField(choices=[('makadiyos', 'Maka-Diyos'), ('makatao', 'Makatao'), ('makakalikasan', 'Makakalikasan'), ('makabansa', 'Makabansa')], max_length=20)),
                ('rating', models.IntegerField(choices=[(4, 'Advanced (4)'), (3, 'Proficient (3)'), (2, 'Approaching Proficiency (2)'), (1, 'Developing (1)')])),
                ('quarter', models.IntegerField(help_text='Quarter (1-4)')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values_grades', to='accounts.classroom')),
                ('graded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graded_core_values', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quarter', 'value_type'],
                'unique_together': {('student', 'classroom', 'value_type', 'quarter')},
            },
        ),
    ]
