# Generated by Django 4.2.30 on 2026-05-03 08:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_corevaluesgrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('call', 'Phone Call'), ('meeting', 'In-Person Meeting'), ('message', 'Message/Text'), ('email', 'Email'), ('note', 'Written Note')], max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('follow_up', 'Follow-up Required'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('parent_name', models.CharField(help_text='Name of parent/guardian', max_length=200)),
                ('parent_contact', models.CharField(blank=True, help_text='Phone number or email', max_length=100, null=True)),
                ('date_scheduled', models.DateTimeField()),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('notes', models.TextField()),
                ('action_items', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications', to='accounts.classroom')),
                ('communicated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communicated_to_parents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_communications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_scheduled', '-created_at'],
            },
        ),
    ]
