# Generated by Django 4.2.30 on 2026-05-04 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_enrollmentapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.CharField(choices=[('home_hero_title', 'Home Hero Title'), ('home_hero_subtitle', 'Home Hero Subtitle'), ('home_announcement_1_title', 'Home Announcement 1 Title'), ('home_announcement_1_content', 'Home Announcement 1 Content'), ('home_announcement_1_date', 'Home Announcement 1 Date'), ('home_announcement_1_category', 'Home Announcement 1 Category'), ('home_announcement_2_title', 'Home Announcement 2 Title'), ('home_announcement_2_content', 'Home Announcement 2 Content'), ('home_announcement_2_date', 'Home Announcement 2 Date'), ('home_announcement_2_category', 'Home Announcement 2 Category'), ('about_mission', 'About Mission'), ('about_vision', 'About Vision'), ('about_history', 'About History'), ('contact_address', 'Contact Address'), ('contact_email', 'Contact Email'), ('contact_phone', 'Contact Phone'), ('contact_office_hours', 'Contact Office Hours')], max_length=100, unique=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['section_key'],
            },
        ),
    ]
