# Generated by Django 4.2.30 on 2026-05-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_websitecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='section_key',
            field=models.CharField(choices=[('home_hero_title', 'Home Hero Title'), ('home_hero_subtitle', 'Home Hero Subtitle'), ('home_announcement_1_title', 'Home Announcement 1 Title'), ('home_announcement_1_content', 'Home Announcement 1 Content'), ('home_announcement_1_date', 'Home Announcement 1 Date'), ('home_announcement_1_category', 'Home Announcement 1 Category'), ('home_announcement_2_title', 'Home Announcement 2 Title'), ('home_announcement_2_content', 'Home Announcement 2 Content'), ('home_announcement_2_date', 'Home Announcement 2 Date'), ('home_announcement_2_category', 'Home Announcement 2 Category'), ('announcement_details_title', 'Announcement Details Title'), ('announcement_details_content', 'Announcement Details Content'), ('announcement_details_date', 'Announcement Details Date'), ('announcement_details_category', 'Announcement Details Category'), ('about_mission', 'About Mission'), ('about_vision', 'About Vision'), ('about_history', 'About History'), ('contact_address', 'Contact Address'), ('contact_email', 'Contact Email'), ('contact_phone', 'Contact Phone'), ('contact_office_hours', 'Contact Office Hours')], max_length=100, unique=True),
        ),
    ]
