# Generated by Django 4.2.30 on 2026-05-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_websitecontent_section_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentapplication',
            name='birth_certificate',
            field=models.FileField(blank=True, null=True, upload_to='enrollment_documents/birth_certificates/'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='certificate_of_completion',
            field=models.FileField(blank=True, help_text='Grade 10 Candidate for Completion Certificate', null=True, upload_to='enrollment_documents/completion_certificates/'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='form_138',
            field=models.FileField(blank=True, help_text='Grade 6 Candidate for Graduation Certificate', null=True, upload_to='enrollment_documents/form_138/'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='good_moral_certificate',
            field=models.FileField(blank=True, null=True, upload_to='enrollment_documents/good_moral/'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='is_als',
            field=models.BooleanField(default=False, help_text='Alternative Learning System applicant'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='last_school_attended_cert',
            field=models.FileField(blank=True, help_text='For ALS applicants', null=True, upload_to='enrollment_documents/last_school/'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='report_card',
            field=models.FileField(blank=True, null=True, upload_to='enrollment_documents/report_cards/'),
        ),
    ]
