# Generated by Django 4.2.30 on 2026-05-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_websitecontent_section_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'ordering': ['section']},
        ),
        migrations.RemoveField(
            model_name='websitecontent',
            name='section_key',
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='section',
            field=models.CharField(blank=True, choices=[('home_hero_title', 'Home Hero Title'), ('home_hero_subtitle', 'Home Hero Subtitle'), ('home_announcement_1_title', 'Home Announcement 1 Title'), ('home_announcement_1_content', 'Home Announcement 1 Content'), ('home_announcement_1_date', 'Home Announcement 1 Date'), ('home_announcement_2_title', 'Home Announcement 2 Title'), ('home_announcement_2_content', 'Home Announcement 2 Content'), ('home_announcement_2_date', 'Home Announcement 2 Date'), ('home_announcement_3_title', 'Home Announcement 3 Title'), ('home_announcement_3_content', 'Home Announcement 3 Content'), ('home_announcement_3_date', 'Home Announcement 3 Date'), ('about_title', 'About Title'), ('about_content', 'About Content'), ('contact_title', 'Contact Title'), ('contact_content', 'Contact Content'), ('programs_title', 'Programs Title'), ('programs_subtitle', 'Programs Subtitle'), ('programs_academic_title', 'Academic Programs Title'), ('programs_academic_content', 'Academic Programs Content'), ('programs_tech_title', 'Technical Programs Title'), ('programs_tech_content', 'Technical Programs Content'), ('programs_sports_title', 'Sports Programs Title'), ('programs_sports_content', 'Sports Programs Content'), ('programs_arts_title', 'Arts Programs Title'), ('programs_arts_content', 'Arts Programs Content')], max_length=100, null=True, unique=True),
        ),
    ]
