# Generated by Django 4.2.30 on 2026-05-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_websitecontent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
