# Generated by Django 4.2.30 on 2026-05-15 01:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_is_approved_user_is_verified_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1'), (2, 'Q2'), (3, 'Q3'), (4, 'Q4')])),
                ('school_year', models.CharField(default='2025-2026', max_length=20)),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_subjects', models.IntegerField(default=0)),
                ('passed_subjects', models.IntegerField(default=0)),
                ('failed_subjects', models.IntegerField(default=0)),
                ('overall_remarks', models.TextField(blank=True, null=True)),
                ('class_rank', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('is_final', models.BooleanField(default=False, help_text='Final report for the school year')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_grade_reports', to='accounts.classroom')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_grade_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-school_year', '-quarter', 'student__username'],
                'unique_together': {('student', 'classroom', 'quarter', 'school_year')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('written_work', 'Written Work'), ('performance_task', 'Performance Task'), ('quarterly_assessment', 'Quarterly Assessment'), ('final_grade', 'Final Grade')], default='written_work', max_length=30)),
                ('quarter', models.IntegerField(choices=[(1, 'First Quarter'), (2, 'Second Quarter'), (3, 'Third Quarter'), (4, 'Fourth Quarter')])),
                ('raw_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_score', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('transmuted_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('computed_remarks', models.CharField(blank=True, max_length=50, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Prevents further edits after submission')),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='accounts.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='accounts.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_subject_grades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-quarter', 'subject__name', 'grade_type'],
                'unique_together': {('student', 'subject', 'grade_type', 'quarter')},
            },
        ),
    ]
