# Generated by Django 4.2.30 on 2026-05-15 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_gradereport_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='accounts.classroom')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_subjects', to='accounts.subject')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_classroom_subjects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['classroom__name', 'subject__name'],
                'unique_together': {('classroom', 'subject')},
            },
        ),
    ]
