# Generated by Django 4.2.30 on 2026-05-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_classroomsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='units',
        ),
    ]
