# Generated by Django 4.2.30 on 2026-05-15 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_remove_subject_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomsubject',
            name='pt_weight',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Performance Task weight (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='classroomsubject',
            name='qa_weight',
            field=models.DecimalField(decimal_places=2, default=20.0, help_text='Quarterly Assessment weight (%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='classroomsubject',
            name='ww_weight',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Written Work weight (%)', max_digits=5),
        ),
    ]
