# Generated by Django 4.2.30 on 2026-05-16 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_announcementattachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-academic_year', '-quarter', 'subject__name', 'grade_type']},
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grade',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'subject', 'grade_type', 'quarter', 'academic_year')},
        ),
    ]
