# Generated by Django 4.2.30 on 2026-05-17 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_profile_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='corevaluesgrade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='corevaluesgrade',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='corevaluesgrade',
            name='graded_by',
        ),
        migrations.RemoveField(
            model_name='corevaluesgrade',
            name='student',
        ),
        migrations.RemoveField(
            model_name='parentcommunication',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='parentcommunication',
            name='communicated_by',
        ),
        migrations.RemoveField(
            model_name='parentcommunication',
            name='student',
        ),
        migrations.DeleteModel(
            name='AnecdotalRecord',
        ),
        migrations.DeleteModel(
            name='CoreValuesGrade',
        ),
        migrations.DeleteModel(
            name='ParentCommunication',
        ),
    ]
