# Generated by Django 4.2.30 on 2026-05-17 14:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='pinned_by',
            field=models.ManyToManyField(blank=True, related_name='pinned_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='friendship',
            name='is_pinned_by_from',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendship',
            name='is_pinned_by_to',
            field=models.BooleanField(default=False),
        ),
    ]
