# Generated by Django 4.2.30 on 2026-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_chatmessage_is_pinned_chatroom_pinned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
