# Generated by Django 5.2.14 on 2026-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_add_created_by_to_chatroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'ordering': ['category', 'section'], 'verbose_name': 'Website Content', 'verbose_name_plural': 'Website Contents'},
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='category',
            field=models.CharField(choices=[('home', 'Home Page'), ('about', 'About Page'), ('contact', 'Contact Page'), ('programs', 'Programs Page'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='section',
            field=models.CharField(blank=True, choices=[('home_hero_title', 'Home Hero Title'), ('home_hero_subtitle', 'Home Hero Subtitle'), ('home_feature_1_title', 'Home Feature 1 Title'), ('home_feature_1_content', 'Home Feature 1 Content'), ('home_feature_2_title', 'Home Feature 2 Title'), ('home_feature_2_content', 'Home Feature 2 Content'), ('home_feature_3_title', 'Home Feature 3 Title'), ('home_feature_3_content', 'Home Feature 3 Content'), ('about_title', 'About Title'), ('about_subtitle', 'About Subtitle'), ('about_mission_title', 'About Mission Title'), ('about_mission_content', 'About Mission Content'), ('about_vision_title', 'About Vision Title'), ('about_vision_content', 'About Vision Content'), ('about_history_title', 'About History Title'), ('about_history_content', 'About History Content'), ('contact_title', 'Contact Title'), ('contact_subtitle', 'Contact Subtitle'), ('contact_address', 'Contact Address'), ('contact_email', 'Contact Email'), ('contact_phone', 'Contact Phone'), ('contact_map_url', 'Contact Map URL'), ('programs_title', 'Programs Title'), ('programs_subtitle', 'Programs Subtitle'), ('programs_academic_title', 'Academic Programs Title'), ('programs_academic_content', 'Academic Programs Content'), ('programs_tech_title', 'Technical Programs Title'), ('programs_tech_content', 'Technical Programs Content'), ('programs_sports_title', 'Sports Programs Title'), ('programs_sports_content', 'Sports Programs Content'), ('programs_arts_title', 'Arts Programs Title'), ('programs_arts_content', 'Arts Programs Content')], max_length=100, null=True, unique=True),
        ),
    ]
