# Generated by Django 5.2.14 on 2026-05-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_alter_websitecontent_options_websitecontent_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitecontent',
            name='section',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
