# Generated by Django 5.2.14 on 2026-05-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_alter_websitecontent_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website_content/'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
