# Generated by Django 5.2.14 on 2026-05-19 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_chatmessage_parent_message_messagereaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_action_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_action_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='last_action_type',
            field=models.CharField(default='message', max_length=20),
        ),
    ]
