# Generated by Django 5.2.14 on 2026-05-20 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_profile_lrn_emailverificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='code',
        ),
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='otp',
            name='hashed_code',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='otp',
            name='otp_type',
            field=models.CharField(choices=[('signup', 'Signup'), ('password_reset', 'Password Reset')], default='signup', max_length=20),
        ),
    ]
