# Generated by Django 5.2.14 on 2026-05-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_remove_otp_code_otp_expires_at_otp_hashed_code_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationToken',
        ),
    ]
