# Generated by Django 5.2.14 on 2026-05-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='expiration_date',
            new_name='event_date',
        ),
    ]
