# Generated by Django 4.2.30 on 2026-05-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20260521_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_password_storage',
            field=models.CharField(blank=True, help_text='Stored temporary password until first login/change', max_length=128, null=True),
        ),
    ]
