# Generated by Django 5.2.14 on 2026-05-22 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_set_db_cascade_on_user_relations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='teacher',
            field=models.OneToOneField(blank=True, help_text='The advisory teacher for this classroom. Each teacher can only have one advisory classroom.', limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_classroom', to=settings.AUTH_USER_MODEL),
        ),
    ]
