# Generated by Django 5.2.14 on 2026-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_fix_classroom_teacher_uniqueness'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='grade_level',
            field=models.CharField(blank=True, help_text='Academic grade level for this classroom (e.g., Grade 7)', max_length=20, null=True),
        ),
    ]
