# Generated by Django 5.2.14 on 2026-05-23 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_reportedmessage_resolved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportedmessage',
            name='message_content_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportedmessage',
            name='reported_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reportedmessage',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='accounts.chatmessage'),
        ),
        migrations.AlterField(
            model_name='reportedmessage',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
