# Generated by Django 5.2.14 on 2026-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_fix_empty_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('grade', 'Grade Update'), ('attendance', 'Attendance'), ('fee', 'Fee Reminder'), ('message', 'Message'), ('friend_request', 'Friend Request'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
