# Generated by Django 5.2.14 on 2026-05-29 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_migrate_filefields_to_supabase_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('teacher', 'Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=10)),
                ('has_seen_welcome', models.BooleanField(default=False)),
                ('completed_tutorials', models.JSONField(blank=True, default=list)),
                ('skipped_tutorials', models.JSONField(blank=True, default=list)),
                ('dismissed_tips', models.JSONField(blank=True, default=list)),
                ('checklist_progress', models.JSONField(blank=True, default=dict)),
                ('last_tutorial', models.CharField(blank=True, default='', max_length=100)),
                ('last_step_id', models.CharField(blank=True, default='', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
