# Generated by Django 5.2.14 on 2026-05-30 22:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0071_chatmessage_attachments'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_certificate', 'PSA Birth Certificate'), ('report_card', 'Report Card'), ('form_138', 'Form 138 / Grade 6 Certificate'), ('certificate_of_completion', 'Certificate of Completion'), ('good_moral', 'Good Moral Certificate'), ('id_picture', 'ID Picture'), ('last_school_attended', 'Last School Attended Certificate'), ('other', 'Other Document')], max_length=30)),
                ('file_url', models.URLField(max_length=1000)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('verification_status', models.CharField(choices=[('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('missing', 'Missing')], default='submitted', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Admin notes about this document', null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_type', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20, null=True)),
                ('to_status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Enrollment status histories',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='assigned_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.classroom'),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='enrolled_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='enrollment_number',
            field=models.CharField(blank=True, help_text='Auto-generated ENR-YYYY-XXXXXX', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='enrollment_type',
            field=models.CharField(choices=[('new', 'New Student'), ('returning', 'Returning Student'), ('transferee', 'Transferee'), ('sh_applicant', 'SHS Applicant'), ('parent_assisted', 'Parent-Assisted Enrollment')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='enrollmentapplication',
            name='strand',
            field=models.CharField(blank=True, choices=[('STEM', 'STEM'), ('ABM', 'ABM'), ('HUMSS', 'HUMSS'), ('GAS', 'GAS'), ('TVL-ICT', 'TVL-ICT'), ('TVL-HE', 'TVL-HE'), ('TVL-IA', 'TVL-IA'), ('TVL-AFA', 'TVL-AFA'), ('Sports', 'Sports'), ('Arts & Design', 'Arts & Design')], help_text='Required for Grades 11-12', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('pending_requirements', 'Pending Requirements'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('enrolled', 'Enrolled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['status'], name='accounts_en_status_f24d2f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['enrollment_number'], name='accounts_en_enrollm_c9e064_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollmentapplication',
            index=models.Index(fields=['grade_level'], name='accounts_en_grade_l_127727_idx'),
        ),
        migrations.AddField(
            model_name='enrollmentdocument',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.enrollmentapplication'),
        ),
        migrations.AddField(
            model_name='enrollmentstatushistory',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='accounts.enrollmentapplication'),
        ),
        migrations.AddField(
            model_name='enrollmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
