# Generated by Django 5.2.14 on 2026-05-30 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0072_enrollment_workflow_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
