# Generated by Django 5.2.14 on 2026-06-09 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_fix_lrn_request_reason_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enrollmentapplication',
            new_name='accounts_en_school__6328e8_idx',
            old_name='accounts_enr_school__idx',
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='classroom',
            field=models.ForeignKey(blank=True, help_text='Scope this time slot to a specific section. Null = universal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='accounts.classroom'),
        ),
        migrations.AlterField(
            model_name='parentlink',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='timeslot',
            unique_together={('classroom', 'day', 'start_time', 'end_time')},
        ),
    ]
