# Generated by Django 5.2.14 on 2026-06-09 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_timeslot_add_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentapplication',
            name='strand',
            field=models.CharField(blank=True, choices=[('Academic', 'Academic Track'), ('TechPro', 'Technical-Professional Track')], help_text='Required for Grades 11-12', max_length=20, null=True),
        ),
    ]
