# Generated by Django 5.2.14 on 2026-06-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0083_departmentcontact_ticket_ticketattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_title',
            field=models.CharField(blank=True, choices=[('teacher', 'Teacher'), ('registrar', 'Registrar'), ('advisory', 'Advisory'), ('principal', 'Principal'), ('guidance_counselor', 'Guidance Counselor'), ('it_staff', 'IT Staff'), ('librarian', 'Librarian'), ('cashier', 'Cashier'), ('other', 'Other')], db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingstate',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('student', 'Student'), ('parent', 'Parent')], db_index=True, default='student', max_length=10),
        ),
    ]
