# Generated by Django 5.2.14 on 2026-06-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0088_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_status_cat_time',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_status_audience',
        ),
        migrations.RemoveIndex(
            model_name='announcement',
            name='idx_announce_event_date',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chatmsg_room_time',
        ),
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='idx_chatmsg_room_read_time',
        ),
        migrations.RemoveIndex(
            model_name='fee',
            name='idx_fee_student_status',
        ),
        migrations.RemoveIndex(
            model_name='fee',
            name='idx_fee_due_status',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='idx_friendship_status',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='idx_friendship_from_status',
        ),
        migrations.RemoveIndex(
            model_name='friendship',
            name='idx_friendship_to_status',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_year_student',
        ),
        migrations.RemoveIndex(
            model_name='grade',
            name='idx_grade_student_subject_year',
        ),
        migrations.RemoveIndex(
            model_name='reportedmessage',
            name='idx_report_status_time',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='idx_schedule_teacher_active',
        ),
        migrations.RemoveIndex(
            model_name='schedule',
            name='idx_schedule_class_active',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='idx_ticketmsg_ticket_time',
        ),
        migrations.RemoveIndex(
            model_name='ticketmessage',
            name='idx_ticketmsg_sender_time',
        ),
        migrations.RemoveIndex(
            model_name='ticketparticipant',
            name='idx_ticketpart_user',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='accounts_ti_status_4aa8cc_idx',
            old_name='ticket_status_cat_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='accounts_ti_created_f546ab_idx',
            old_name='ticket_creator_status_idx',
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='academic_level',
            field=models.CharField(choices=[('jhs', 'Junior High School (Grades 7-10)'), ('shs', 'Senior High School (Grades 11-12)')], default='jhs', max_length=3),
        ),
    ]
