# Generated by Django 5.2.14 on 2026-06-14 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0089_add_academic_level_to_systemsetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='transmuted_score',
        ),
    ]
