# Generated by Django 4.2.30 on 2026-05-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_apirequestlog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='grade',
            name='course',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
