# Generated by Django 5.2.14 on 2026-05-21 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_alter_grade_unique_together_remove_grade_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action_type',
            field=models.CharField(blank=True, choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View'), ('export', 'Export'), ('import', 'Import'), ('grade_create', 'Grade Create'), ('grade_update', 'Grade Update'), ('grade_delete', 'Grade Delete'), ('attendance_mark', 'Attendance Mark'), ('attendance_delete', 'Attendance Delete'), ('mute', 'User Mute'), ('suspend', 'User Suspend')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_type', models.CharField(choices=[('1st', 'First Semester'), ('2nd', 'Second Semester'), ('summer', 'Summer')], max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='portal.academicyear')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'semester_type'],
                'unique_together': {('academic_year', 'semester_type')},
            },
        ),
    ]
