services:
  - type: web
    name: knhs-backend
    env: python
    buildCommand: ./build.sh
    startCommand: daphne -b 0.0.0.0 -p $PORT school_portal.asgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: DATABASE_URL
        sync: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "cranoraa-knhs-website-1.onrender.com,localhost,127.0.0.1"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://cranoraa-knhs-website.vercel.app,http://localhost:5173"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://cranoraa-knhs-website.vercel.app"
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
